os: linux
sudo: true
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,simplejson,devel,lowest,codecov
    - python: 3.6
      env: TOXENV=docs-html
    - python: 3.5
      env: TOXENV=py,codecov
    - python: 3.4
      env: TOXENV=py,codecov
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  allow_failures:
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install python3 redis memcached;
      virtualenv -p python3 ~/py-env;
      . ~/py-env/bin/activate;
    fi

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false

addons:
  chrome: stable
